# Site settings
title: kablamo
description: > # this means to ignore newlines until "baseurl:"
  Eric is a Chicago based developer who has been building stuff with Perl since
  1998.  Currently he is building stuff at DuckDuckGo.  Eric has lived and
  worked in Beijing, Singapore, and London.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kablamo.org" # the base hostname & protocol for your site
twitter_username: kablamo_
github_username:  kablamo

# Build settings
markdown: kramdown
