# Site settings
title: kablamo
description: > # this means to ignore newlines until "baseurl:"
  Eric is a Chicago based developer who has been building stuff with Perl since
  1998.  Currently he is building stuff at DuckDuckGo.  Eric has lived and
  worked in Beijing, Singapore, and London.  He enjoys peanut butter and ice
  cream and peanut butter ice cream.
permalink: /:year/:month/:day/:title/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kablamo.org" # the base hostname & protocol for your site

category_archive:
    path: categories

twitter_username: kablamo_
github_username:  kablamo

pinboard_user: kablamo
pinboard_count: 20 

disqus_short_name: kablamo
disqus_show_comment_count: false

google_analytics_tracking_id:

disqus_short_name: kablamo
disqus_show_comment_count: false

# Build settings
markdown: kramdown
